name: google_maps_distance
description: Calculate distances, durations & Get shortest route/leg between two points.
version: 0.0.1
homepage: https://pub.dev/packages/google_maps_distance

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
